[build]
  command = """
    bash -c '
      curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.0-stable.tar.xz | tar xJ -C ~/
      export PATH=$PATH:$HOME/flutter/bin
      flutter --version
      flutter pub get
      flutter build web --release
    '
  """
  publish = "build/web"
